### ISSUE TITLE
Coreference resolution with key term

### ISSUE THREAD

**Issue by csieff** [NeuroSYS-pl/coreference-resolution#2]
Many thanks for sharing your coreference resolution code and blog series, it's fantastic! I was hoping to follow up to ask your advice on other possible coreference resolution packages that I could use to adapt the code. We're hoping to adapt it in two ways:

1) I’ve been trying to only replace mentions that include a key term (“roomba"). I'd been thinking perhaps I could modify your solution to redundant clusters so that it only returns key term clusters as meaningful clusters, skipping over the rest. Just in case it'd be a useful illustration (putting code in words isn't always the easiest...), I attached a screenshot of the adapted code. Unfortunately, when I adapted it I haven't been able to get it to return just those clusters. Do you happen to know of any packages that only replace clusters if they contain a key term?

2) Very similarly, I'm trying to make sure that if the key term is contained in a cluster, it's returned as the head of the cluster (e.g. in a cluster of "this item," "it", and "roomba," I'm trying to replace everything with "roomba" instead of "this item"). I was thinking I could adapt the get_cluster_head function, but unfortunately I again can't get it to work. I was wondering if you happen to know of any packages that prioritize a key term as the head of a cluster?

A downside of the approach I was trying out is that it ties the two together (it would use the clusters from 1 in 2), but I'm sure there's also ways to approach it where you could do 2 but not 1 (or vice-versa). 

Thanks a ton for your advice on this and again for sharing these resources, it's very appreciated!

![image](https://user-images.githubusercontent.com/82617879/119384003-10eac300-bc92-11eb-8f20-b70ddd3c48e6.png)

![image](https://user-images.githubusercontent.com/82617879/119383954-ffa1b680-bc91-11eb-9720-1d9d49dde2d7.png)

**Comment by mmaslankowska-neurosys** [comment]
Hi! We're really glad that our solutions to coreference resolution can be helpful :blush: 

Thank you for such a detailed description of your problem. It was a good call to try to reimplement the `get_span_noun_indices` function. Because I believe just this function can help you achieve your both goals :wink:   
It's responsible for filtering out clusters that don't contain any noun phrases. Furthermore, our `get_cluster_head` function treats the first found noun phrase as a cluster head. So if you reimplement `get_span_noun_indices` so that it filters out clusters that don't contain the term "roomba", `get_cluster_head` can remain unchanged. Exactly as you tried - you should replace the filtering condition: instead of noun phrases you want to detect the word "roomba".

```python
def get_roomba_indices(doc: Doc, cluster: List[List[int]]) -> List[int]:
    spans = [doc[span[0]:span[1]+1] for span in cluster]
    spans_text = [[token.lower_ for token in span] for span in spans]
    span_roomba_indices = [i for i, span_text in enumerate(spans_text) if 'roomba' in span_text]
    return span_roomba_indices
```
### An example
Assume we have the following text: (as I understand, we're interested only in marked cluster 0. )
![allen_demo](https://user-images.githubusercontent.com/77386734/119474255-40f69c80-bd4c-11eb-8b9b-451a83f8e332.png)

Our initial improvements would filter out clusters 1 and 2, leaving cluster 0 with *This item* as its head and cluster 3 with *Our sales personnel Tom and Jake*. The text would look like this:  
**`This item`**`is brand new on the market! Do you know what`**`This item`**`is? I'll tell you:`**`This item`**`is the new revolutionary vacuum.`**`Our sales personnel Tom and Jake`**`can tell you all the details.`**`Our sales personnel Tom and Jake`**`will answer your every question.`

I believe you would like to filter out cluster 3 as well and in cluster 0 set *Roomba* (the third span) as its head. Replacing our `get_span_noun_indices` with the above `get_roomba_indices` function gives me the following output:  
**`Roomba`**`is brand new on the market! Do you know what`**`Roomba`**`is? I'll tell you:`**`Roomba`**`is the new revolutionary vacuum. Our sales personnel Tom and Jake can tell you all the details. They will answer your every question.`

I attach a more detailed Jupyter Notebook file here (zipped) - [allennlp_roomba.zip](https://github.com/NeuroSYS-pl/coreference-resolution/files/6538071/allennlp_roomba.zip). Hope it works for you! :smiley:

**Comment by csieff** [comment]
Hi!
I can't say thanks enough for your advice on this! It's such a brilliant solution, I'm very grateful to you for taking the time to share this really detailed jupyter notebook. It truly solves so many questions 😃
Thank you again for everything, I incredibly appreciate it!
