### ISSUE TITLE
more run time

### ISSUE THREAD

**Issue by krishna-anumula** [NeuroSYS-pl/coreference-resolution#4]
I am doing bootstrap sampling on my text data and finding relevant coref solution using your updated "improvements to allennlp_cr", sometimes it is abruptly getting terminated, don't know the issue. Followed all the steps given by you it will work for some of the texts.

Any solution regarding this ASAP.

**Comment by mmaslankowska-neurosys** [comment]
Hi,
in order to be able to help you, we would have to know some more details :slightly_smiling_face: Nobody mentioned such problems before so we don't have a clue what could possibly have gone wrong in your case. Could you provide us a specification of your environment? (system version, python and other packages versions, etc. - anything that could help us identify the problem)

**Comment by krishna-anumula** [comment]
using visual studio for my project.
Python - 3.8.10
Spacy - 2.3.7
pytorch - 1.9.1+cu102

**Comment by krishna-anumula** [comment]
Are there any limitations for text length, type of text etc. Because I am using articles and blogs texts for this. For nearly 300 items it works fine as of now, but for the 40-50 articles it is not working.

**Comment by mmaslankowska-neurosys** [comment]
We didn't encounter any limitations regarding text length except that if you pass a text shorter than 2 words (spacy tokens), AllenNLP will throw an error.

However, we've encountered multiple problems with `spacy` itself - as mentioned in our [`README`](https://github.com/NeuroSYS-pl/coreference-resolution#installation) we use `spacy` in version `2.1.0` whereas you have `2.3.7` installed. I would recommend installing the older version to see whether this solves your problem.

**Comment by krishna-anumula** [comment]
![crop](https://user-images.githubusercontent.com/90172400/134497514-281a5ad8-46b2-456a-bff2-b042ca8f0346.png)
Here is the image if I downgrade spacy and running the file, this is the error i am facing

**Comment by mmaslankowska-neurosys** [comment]
I've checked this issue and indeed (as mentioned in [this comment](https://stackoverflow.com/a/62852223) which seems related to your problem) `neuralcoref` works only with Python `3.7`. As you use `3.8.10` you'd have to downgrade Python version and check whether this helps :slightly_smiling_face:

**Comment by krishna-anumula** [comment]
If there is any issue with versions, then it is working fine for some of the texts earlier right..? Why it is not working only for some

**Comment by mmaslankowska-neurosys** [comment]
We've encountered many weird and unusual problems - that usually were associated with library versions - while developing our coreference resolution project. That's why I advise you to try experimenting with them. We've found this single combination of library versions that worked perfectly for our use and with which we didn't have any more problems.

However, you're right that your problem could be caused by some other issue as for some cases it works and for some others don't. Unfortunately, I can't think of any other solution (than experimenting with the versions) that could address this problem. 

There can be something wrong with the input data - you can try to check out [AllenNLP](https://demo.allennlp.org/coreference-resolution) and [Neuralcoref](https://huggingface.co/coref/) demos and check whether it works when you manually try to resolve coreferences this way.   
If it's not related to your data, you can try to check whether the issue is caused by AllenNLP library, Huggingface Neuralcoref library, or by our improvements from the `improvements_to_allennlp_cr`. Except for the latter, I'm afraid we won't be able to help, as our improvements only extend AllenNLP and Huggingface projects. 

Hope you'll find what's wrong (or at least a way how to run the code) :slightly_smiling_face:

**Comment by krishna-anumula** [comment]
I found that issue is not with versions rather with text length. I found that text which is having minimum of 10500 length is not working.

**Comment by mmaslankowska-neurosys** [comment]
Thanks for letting us know what the source of the problem was. Glad you've found it :blush: We never process such long texts so we wouldn't have known about this issue otherwise.
